using System.Collections.Concurrent;
using System.ComponentModel;
using System.Text;
using Microsoft.Extensions.AI;

using AzureFinOps.Dashboard.Infrastructure;

namespace AzureFinOps.Dashboard.AI.Tools;

/// <summary>
/// Generates downloadable Azure CLI / PowerShell scripts from FinOps recommendations.
/// The LLM produces the script content after discussing with the user, and this tool
/// packages it as a downloadable .ps1 or .sh file with a code preview in the UI.
/// </summary>
public static class ScriptTools
{
    // Store generated files for download: fileId → (path, created, content)
    internal static readonly ConcurrentDictionary<string, (string Path, DateTime Created, string Content)> GeneratedFiles = new();

    internal static void CleanupOldFiles() =>
        TempFileHelper.CleanupOldFiles(GeneratedFiles, v => v.Created, v => v.Path);

    public static IEnumerable<AIFunction> Create()
    {
        yield return AIFunctionFactory.Create(GenerateScript, "GenerateScript",
            @"Generates a downloadable Azure CLI or PowerShell script from FinOps recommendations.
Call this ONLY after you have:
1. Already analyzed the user's Azure environment and found actionable recommendations (e.g., orphaned resources, untagged resources, right-sizing, idle VMs, unattached disks, missing budgets, etc.)
2. Discussed the specific recommendations with the user and confirmed they want a script generated.

If the conversation has no actionable recommendations yet, do NOT call this tool. Instead, tell the user:
'I don't have any actionable recommendations to script yet. Let me first analyze your environment to find optimization opportunities.'

The script should implement the specific FinOps actions discussed (e.g., delete orphaned disks, apply tags, resize VMs, set budgets).
Always include safety features: --what-if or confirmation prompts, comments explaining each step, and a dry-run mode.
Prefer Azure CLI (az) scripts unless the user specifically asks for PowerShell.");
    }

    private static Task<string> GenerateScript(
        [Description(@"The full script content (Azure CLI or PowerShell). Must include:
- A header comment block explaining what the script does, prerequisites, and usage
- Safety features: dry-run mode, confirmation prompts, or --what-if flags
- Clear comments for each logical section
- Error handling for critical operations
Example header:
#!/bin/bash
# FinOps Remediation Script: Delete Orphaned Disks
# Generated by Azure FinOps Agent
# Prerequisites: Azure CLI 2.50+, logged in via 'az login'
# Usage: chmod +x script.sh && ./script.sh
# Mode: DRY-RUN by default — set DRY_RUN=false to execute")] string scriptContent,
        [Description("Filename for the script (without extension). Default: 'finops-remediation'")] string? filename,
        [Description("Script language: 'bash' for .sh (Azure CLI), 'powershell' for .ps1. Default: 'bash'")] string? language,
        [Description("Brief description of what the script does (shown in the UI download button)")] string? description)
    {
        if (string.IsNullOrWhiteSpace(scriptContent))
            return Task.FromResult("Error: No script content provided.");

        CleanupOldFiles();

        var lang = (language ?? "bash").ToLowerInvariant();
        var ext = lang == "powershell" ? ".ps1" : ".sh";
        var fileId = Guid.NewGuid().ToString("N")[..12];
        var safeName = string.IsNullOrWhiteSpace(filename) ? "finops-remediation" : SanitizeFilename(filename);
        var outputPath = Path.Combine(Path.GetTempPath(), $"{fileId}_{safeName}{ext}");
        var desc = string.IsNullOrWhiteSpace(description) ? "FinOps remediation script" : description;

        File.WriteAllText(outputPath, scriptContent, Encoding.UTF8);

        GeneratedFiles[fileId] = (outputPath, DateTime.UtcNow, scriptContent);

        var lineCount = scriptContent.Split('\n').Length;

        return Task.FromResult($"__SCRIPT_READY__:{fileId}:{safeName}{ext}:{lineCount}:{lang}:{desc}");
    }

    private static string SanitizeFilename(string name) =>
        TempFileHelper.SanitizeFilename(name, "finops-remediation");
}
